# cerebro lib: backend-opencode
# The opencode backend: drives the orchestrator and editing children through
# the opencode CLI. Children run as `opencode run --agent <name> --format json`,
# and the orchestrator runs as `opencode --agent <name>`. Agent role prompts +
# permissions live in opencode agent markdown files under
# $CEREBRO_HOME/.opencode/agent/, generated by payloads.sh. Pair mode drives a
# child under a private headless `opencode serve`.
# Sourced by bin/cerebro via backend.sh; not meant to be executed directly.

# backend_opencode_child_run_opts <agent> <resume-id> <model> -- build the
# `opencode run` flag array for a child into the caller-scoped CHILD_RUN_OPTS.
# We pass --format json so opencode streams its event objects (parsed by
# parse_stream.py), --dangerously-skip-permissions so the non-interactive child
# never blocks on an approval prompt, the model, and --session to resume an
# in-flight child.
backend_opencode_child_run_opts() {
  local agent="$1" resume="${2:-}" model="${3:-}"
  CHILD_RUN_OPTS=(run --agent "$agent" --format json --dangerously-skip-permissions)
  [[ -n "$model" ]] && CHILD_RUN_OPTS+=(--model "$model")
  [[ -n "$resume" ]] && CHILD_RUN_OPTS+=(--session "$resume")
}

# backend_opencode_child_run <pair> <cwd> <prompt> <agent> <resume-id>
#   <child_log> <msg_capture> <id_capture> <store_file> <ckey> [model] -- run
# one attempt of an opencode child and return its exit code. Unpaired FRESH
# child: launch `opencode run` with the prompt as its positional message, tee
# the JSON event stream to <child_log>, and pipe it through parse_stream.py.
# Unpaired RESUME (non-empty <resume-id>): `opencode run --session <id>` is
# broken on resume -- in opencode >=1.17 it completes the turn (the model
# runs, tools fire, "exiting loop" is logged) but writes NO run-json events to
# stdout and never exits the process, so parse_stream's idle timer fires a
# false "stalled" on a child that already finished its work. We therefore
# drive a resume through the same headless `opencode serve` + SSE pump the
# paired path uses (POST /prompt + /event stream), which streams run-format
# events and exits cleanly on session.idle. Paired: hand off to
# backend_opencode_pair_run, which already drives the child through a serve.
backend_opencode_child_run() {
  local pair="$1" cwd="$2" prompt="$3" agent="$4" resume="$5" \
        child_log="$6" msg_capture="$7" id_capture="$8" store_file="$9" ckey="${10}"
  local model="${11:-$CEREBRO_MODEL}"

  if (( pair )); then
    backend_opencode_pair_run "$cwd" "$prompt" "$agent" "$resume" \
      "$child_log" "$msg_capture" "$id_capture" "$store_file" "$ckey" "$model"
    return $?
  fi

  if [[ -n "$resume" ]]; then
    backend_opencode_resume_run "$cwd" "$prompt" "$agent" "$resume" \
      "$child_log" "$msg_capture" "$id_capture" "$store_file" "$ckey" "$model"
    return $?
  fi

  backend_opencode_child_run_opts "$agent" "" "$model"
  local err_log="${child_log%.log}.err.log"
  ( cd "$cwd" && env -u CEREBRO_SESSION_ID -u CEREBRO_SESSION_DIR \
      "${TIMEOUT_CMD[@]}" "$CEREBRO_OPENCODE_CMD" "${CHILD_RUN_OPTS[@]}" "$prompt" </dev/null 2>"$err_log" \
      | tee "$child_log" \
      | python3 "$CEREBRO_LIB_DIR/python/parse_stream.py" \
          "$msg_capture" "$id_capture" "$store_file" "$ckey" )
  return $?
}

# backend_opencode_resume_run <cwd> <prompt> <agent> <resume-id> <child_log>
#   <msg_capture> <id_capture> <store_file> <ckey> [model] -- drive a one-shot
# unpaired RESUME of an opencode session through a transient headless
# `opencode serve`. `opencode run --session <id>` does not stream on resume (see
# backend_opencode_child_run), so we reuse the serve + SSE pump that the paired
# path proved works for resume: start a private server rooted at <cwd>, feed the
# prompt to the existing session <resume-id>, stream its run-format events to
# stdout (teed to <child_log>, piped through parse_stream.py), and exit on the
# first session.idle. No steering fifo window: the pump's idle grace is set to
# 0 so it exits the instant the turn completes (a resume is single-turn; any
# further turn is a separate `cerebro answer`). The pump's own stall markers
# (`.stalled` / `.restart`) are honored by the same pair_stalled logic the
# command files already use for the paired path, so a genuinely frozen resume is
# still detectable.
backend_opencode_resume_run() {
  local cwd="$1" prompt="$2" agent="$3" resume="$4" child_log="$5" \
        msg_capture="$6" id_capture="$7" store_file="$8" ckey="$9" \
        model="${10:-$CEREBRO_MODEL}"
  local port serve_pid base_url fifo steer pump_log rc
  port="$(backend_opencode_pair_free_port)"
  base_url="http://127.0.0.1:$port"
  ( cd "$cwd" && exec env -u CEREBRO_SESSION_ID -u CEREBRO_SESSION_DIR \
      "$CEREBRO_OPENCODE_CMD" serve --port "$port" --hostname 127.0.0.1 ) \
      >/dev/null 2>&1 &
  serve_pid=$!
  if ! python3 "$CEREBRO_LIB_DIR/python/serve_ctl.py" health "$base_url"; then
    # Soft-fail (do not die): a non-functional opencode serve -- e.g. an
    # `opencode` stub in tests, or a broken install -- surfaces as a non-zero
    # resume rc with no captured id, so the command files' stale-fallback path
    # can retry the child fresh, matching how a rejected `opencode run --session`
    # used to fail.
    kill "$serve_pid" 2>/dev/null
    warn "resume: opencode serve did not come up on port $port"
    return 2
  fi
  fifo="${child_log%.jsonl}.steer.fifo"
  steer="${child_log%.jsonl}.steering.md"
  pump_log="${child_log%.jsonl}.pump.log"
  : > "$steer"
  rm -f "$fifo"
  mkfifo "$fifo" || { kill "$serve_pid" 2>/dev/null; warn "resume: cannot create steering pipe at $fifo"; return 2; }
  # The pump opens the fifo O_RDWR itself, so it never sees EOF even with no
  # external writer. idle_grace=0: a resume is single-turn, so exit the instant
  # the turn goes idle (no steering window). The two stall windows stay at their
  # defaults so a genuinely frozen turn is still flagged via the pump's
  # `.stalled` marker.
  printf '%s' "$prompt" \
    | python3 "$CEREBRO_LIB_DIR/python/pair_pump_opencode.py" \
        "$base_url" "$resume" "$agent" "$model" \
        "$fifo" "$steer" "$child_log" 0 \
        "${CEREBRO_PAIR_STALL:-180}" "${CEREBRO_PAIR_STALL_BUSY:-450}" 2>"$pump_log" \
    | tee "$child_log" \
    | python3 "$CEREBRO_LIB_DIR/python/parse_stream.py" \
        "$msg_capture" "$id_capture" "$store_file" "$ckey"
  rc=$?
  kill "$serve_pid" 2>/dev/null
  rm -f "$fifo"
  return $rc
}

# backend_opencode_child_agent_name <role> -- the opencode agent name for a
# child role (the basename of its agent file under .opencode/agent/). review
# and audit share one read-only reviewer agent.
backend_opencode_child_agent_name() {
  case "$1" in
    execute|apply-review|doc-write|verify) printf 'cerebro-%s\n' "$1" ;;
    review|audit) printf 'cerebro-reviewer\n' ;;
    *) die "backend_opencode_child_agent_name: unknown role: $1" ;;
  esac
}

# backend_opencode_child_provider <role> -- the provider string written to the
# child session store.
backend_opencode_child_provider() { printf 'opencode\n'; }

# backend_opencode_answerable_provider <role> -- the provider:role pattern
# `cerebro answer` accepts for an opencode child.
backend_opencode_answerable_provider() {
  case "$1" in
    execute|apply-review|doc-write|verify) printf 'opencode:%s\n' "$1" ;;
    *) die "backend_opencode_answerable_provider: unknown role: $1" ;;
  esac
}

# backend_opencode_materialise_extras -- the opencode backend has no extra home
# files beyond the shared opencode tree written by materialise_home (agents +
# plugin + base config). No-op.
backend_opencode_materialise_extras() { :; }

# backend_opencode_launch_orchestrator <sess_dir> <agent> -- exec the
# interactive opencode orchestrator. <agent> is the agent name
# (write_orchestrator_agent echoes it). opencode assigns its own session id;
# the cerebro plugin records it into metadata.json so `cerebro --resume` can
# reopen the same conversation. The exported CEREBRO_SESSION_ID binds every
# `cerebro` subcommand the orchestrator runs back to this session.
backend_opencode_launch_orchestrator() {
  local sess_dir="$1" agent="$2"
  local model_opt=(); [[ -n "$CEREBRO_MODEL" ]] && model_opt=(--model "$CEREBRO_MODEL")
  exec "$CEREBRO_OPENCODE_CMD" --agent "$agent" "${model_opt[@]}"
}

# backend_opencode_launch_observer <sess_dir> <agent> <target> -- exec the
# interactive opencode observer. When <target> is non-empty, seed an
# interactive first turn via --prompt so the observer starts narrating
# immediately.
backend_opencode_launch_observer() {
  local sess_dir="$1" agent="$2" target="$3"
  local model_opt=(); [[ -n "$CEREBRO_MODEL" ]] && model_opt=(--model "$CEREBRO_MODEL")
  if [[ -n "$target" ]]; then
    exec "$CEREBRO_OPENCODE_CMD" --agent "$agent" "${model_opt[@]}" \
      --prompt "Start observing session $target now: run \`cerebro observe $target\`, narrate what you see, and keep looping until its children are done or I stop you."
  else
    exec "$CEREBRO_OPENCODE_CMD" --agent "$agent" "${model_opt[@]}"
  fi
}

# backend_opencode_resume_orchestrator <sess_dir> <foreign-id> <agent> -- exec
# the resumed opencode orchestrator. Reopen the same opencode conversation when
# we captured its id at launch; otherwise start a fresh opencode session in this
# same cerebro session dir (cerebro state persists regardless).
backend_opencode_resume_orchestrator() {
  local sess_dir="$1" ocid="$2" agent="$3"
  local model_opt=(); [[ -n "$CEREBRO_MODEL" ]] && model_opt=(--model "$CEREBRO_MODEL")
  if [[ -n "$ocid" ]]; then
    exec "$CEREBRO_OPENCODE_CMD" --session "$ocid" --agent "$agent" "${model_opt[@]}"
  else
    warn "no stored opencode session id for $(basename "$sess_dir"); starting a fresh opencode conversation"
    exec "$CEREBRO_OPENCODE_CMD" --agent "$agent" "${model_opt[@]}"
  fi
}

# ----- pair mode (opencode serve) -------------------------------------------

# pair_free_port -- echo an unused localhost TCP port.
backend_opencode_pair_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

# backend_opencode_pair_begin <role> <repo> <branch> <child_log> [resume-id] --
# start a private headless `opencode serve` rooted at the child's working dir,
# resolve the opencode session id, and set the caller-scoped PAIR_* vars the
# pump reads. Sets: PAIR_SID, PAIR_PORT, PAIR_BASE_URL, PAIR_SERVE_PID,
# PAIR_FIFO, PAIR_STEER, PAIR_IDLE, PAIR_STALL, PAIR_STALL_BUSY.
backend_opencode_pair_begin() {
  local role="$1" repo="$2" branch="${3:-}" child_log="$4" resume="${5:-}"
  local label; label="$(pair_label "$role" "$repo" "$branch")"

  PAIR_PORT="$(backend_opencode_pair_free_port)"
  PAIR_BASE_URL="http://127.0.0.1:$PAIR_PORT"
  ( cd "$repo" && exec env -u CEREBRO_SESSION_ID -u CEREBRO_SESSION_DIR \
      "$CEREBRO_OPENCODE_CMD" serve --port "$PAIR_PORT" --hostname 127.0.0.1 ) \
      >/dev/null 2>&1 &
  PAIR_SERVE_PID=$!
  python3 "$CEREBRO_LIB_DIR/python/serve_ctl.py" health "$PAIR_BASE_URL" \
    || die "pair: opencode serve failed to start on port $PAIR_PORT"

  if [[ -n "$resume" ]]; then
    PAIR_SID="$resume"
  else
    PAIR_SID="$(python3 "$CEREBRO_LIB_DIR/python/serve_ctl.py" create "$PAIR_BASE_URL" "$label")" \
      || die "pair: could not create opencode session on $PAIR_BASE_URL"
  fi

  PAIR_STEER="${child_log%.jsonl}.steering.md"
  PAIR_FIFO="${child_log%.jsonl}.steer.fifo"
  PAIR_IDLE="${CEREBRO_PAIR_IDLE:-60}"
  PAIR_STALL="${CEREBRO_PAIR_STALL:-180}"
  PAIR_STALL_BUSY="${CEREBRO_PAIR_STALL_BUSY:-450}"
  : > "$PAIR_STEER"
  rm -f "$PAIR_FIFO"
  mkfifo "$PAIR_FIFO" || die "pair: cannot create steering pipe at $PAIR_FIFO"
  pair_banner "$role" "$PAIR_SID" "$label" "$PAIR_FIFO"
}

# backend_opencode_pair_run <cwd> <prompt> <agent> <resume> <child_log>
#   <msg_capture> <id_capture> <store_file> <ckey> [model] -- drive a paired
# child to completion under the headless opencode serve. Feeds the initial
# prompt to pair_pump (which POSTs it to the served session and streams the
# session's events back in run-format), tees those events to the child log, and
# pipes them through parse_stream.py. Returns the pump's exit code when it
# failed, otherwise parse_stream's.
backend_opencode_pair_run() {
  local cwd="$1" prompt="$2" agent="$3" resume="$4" child_log="$5" \
        msg_capture="$6" id_capture="$7" store_file="$8" ckey="$9" \
        model="${10:-$CEREBRO_MODEL}"
  local pump_log="${child_log%.jsonl}.pump.log"
  printf '%s' "$prompt" \
    | python3 "$CEREBRO_LIB_DIR/python/pair_pump_opencode.py" \
        "$PAIR_BASE_URL" "$PAIR_SID" "$agent" "$model" \
        "$PAIR_FIFO" "$PAIR_STEER" "$child_log" \
        "$PAIR_IDLE" "$PAIR_STALL" "$PAIR_STALL_BUSY" 2>"$pump_log" \
    | tee "$child_log" \
    | python3 "$CEREBRO_LIB_DIR/python/parse_stream.py" \
        "$msg_capture" "$id_capture" "$store_file" "$ckey"
  local pipe=( "${PIPESTATUS[@]}" )
  (( pipe[1] != 0 )) && return "${pipe[1]}"
  return "${pipe[3]}"
}

# backend_opencode_pair_cleanup <pair> -- stop the private server and remove
# the steering pipe.
backend_opencode_pair_cleanup() {
  (( $1 )) || return 0
  if [[ -n "${PAIR_SERVE_PID:-}" ]]; then
    kill "$PAIR_SERVE_PID" 2>/dev/null
    PAIR_SERVE_PID=""
  fi
  [[ -n "${PAIR_FIFO:-}" ]] && rm -f "$PAIR_FIFO"
}